### PR TITLE
[JBEAP-18192]: Generic RA does not support JMS 1.1

### PR DESCRIPTION
**Pull request by ehsavoie**
* Fixing support for JMS 1.1 vs 2.0 by separating code.
     * Fixing JBEAP-18167 since both code are now separated.

Jira: https://issues.redhat.com/browse/JBEAP-18167
        https://issues.redhat.com/browse/JBEAP-18192

### CODE REVIEW

**Comment by jbertram** [comment]
I'm in the process of reviewing this so please don't merge it yet.

**Comment by jbertram** [comment]
I've got a couple of general questions:

1. What is the role of `org.jboss.resource.adapter.jms.JMSConsumerToMessageConsumer` and `org.jboss.resource.adapter.jms.JMSProducerToMessageProducer`?
2. What is the role of the wrappers `org.jboss.resource.adapter.jms.JmsConnectionSession` and `org.jboss.resource.adapter.jms.JmsConnectionContext`?
3. It looks like there is overlap between  `org.jboss.resource.adapter.jms.JmsManagedConnection#createSession` and the block of code creating sessions in `org.jboss.resource.adapter.jms.JmsManagedConnection#setup`. When the wrapper class mentioned in question 2 is returned from `org.jboss.resource.adapter.jms.JmsManagedConnection#createConnection` it may already have a session created but `setup()` will still try to create a session anyway.

When I thought about a solution to this problem I envisioned a simple boolean flag on the RA to indicate whether or not the underlying JMS client implementation supported JMS 2. If so the RA would create a `JMSContext`. If not the RA wouldn't create a `JMSContext` any client access of the JMS 2 API would result in a `RuntimeException` of some kind.

Lastly, I was having a lot of trouble distinguishing the changes specifically to fix this issue with formatting and other non-relevant improvements so I split your 2 commits into 4 commits and pushed a branch to https://github.com/jbertram/generic-jms-ra/tree/JBEAP-18192. In my opinion it's much easier to read the diffs now and the commit history is much more descriptive as well.

**Comment by ehsavoie** [comment]
1. When we are using JMS 1.1 API over a JMSContext this is to wrap those calls without requiring a Connection from the provider.
2. JmsConnectionSession is a JMS 1.1 Connection over a Connection and Session provided by the provider while JmsConnectionContext is a JMS  1.1 Connection over a JMSContext
3. I see the problem, maybe we could reuse those of the underlying objects.
@jbertram but then you would have both a Connection and a JMSContext so 2 connections to the broker in JMS 2.0 case. 
I agree, I shouldn't have squashed those commits.

**Comment by jbertram** [comment]
> 1. When we are using JMS 1.1 API over a JMSContext this is to wrap those calls without requiring a Connection from the provider.

I'm a bit confused by this. `javax.jms.JMSContext` is exclusive to JMS 2.0. How can this be used with JMS 1.1? Are you wanting to allow the use of `javax.jms.JMSContext` on top of a JMS 1.1 implementation? In my opinion the RA should only support the API version implemented by the underlying client.

> 2. JmsConnectionSession is a JMS 1.1 Connection over a Connection and Session provided by the provider while JmsConnectionContext is a JMS 1.1 Connection over a JMSContext

Again, I don't understand the interplay between JMS 1.1 and `javax.jms.JMSContext`. Can you elaborate on this a bit more?

> I agree, I shouldn't have squashed those commits.

Maybe you could cherry-pick the commits from my branch onto your own branches and send different PRs or at least 1 PR with the different commits. That would make it much easier to review.

**Comment by ehsavoie** [comment]
2. The goal was not to have to create a connection with both JMSContext and a Connection so that a user call would use the correct implementation. if you have a pool of JMSContext then you could still call some 1.1 methods without requiring a different pool or a new entry.
1. No I want to allow JMS 1.1 calls over a JMSContext without requiring the ManagedConnection to also have a Connection ready.
I rebased on your branch

**Pull request merged**
